global:
  scrape_interval: 15s

scrape_configs:
  # Prometheus se scrape lui-meme
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Metriques systeme de la VM (CPU, RAM, disque, reseau)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Metriques Nginx du site web Althea via nginx-exporter
  - job_name: 'althea-app'
    static_configs:
      - targets: ['althea-nginx-exporter:9113']
