global:
  scrape_interval: 15s

scrape_configs:
  # Prometheus se scrape lui-meme
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Metriques systeme de la VM
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Metriques du container web Nginx
  - job_name: 'althea-app'
    static_configs:
      - targets: ['althea-web:80']
